### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by ziviani** [cncjs/cncjs-pendant-keyboard#2]
Hello!
I got this error when I've tried to use cncjs-pendant-keyboard:

pi@cnc:/usr/lib/node_modules/cncjs-pendant-keyboard-master $ bin/cncjs-pendant-keyboard
/usr/lib/node_modules/cncjs-pendant-keyboard ### master/node_modules/serialport/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/build/serialport.node
 → /usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/build/Debug/serialport.node
 → /usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/build/Release/serialport.node
 → /usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/out/Debug/serialport.node
 → /usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/Debug/serialport.node
 → /usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/out/Release/serialport.node
 → /usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/Release/serialport.node
 → /usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/build/default/serialport.node
 → /usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/compiled/4.8.7/linux/arm/serialport.node
    at bindings (/usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/lib/bindings.js:3:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/cncjs-pendant-keyboard-master/node_modules/serialport/lib/serialport.js:12:25)
    at Module._compile (module.js:409:26)

Don't you have an idea how to solve this problem?
Regards,
Ziviani

**Comment by cassioeskelsen** [comment]
You must install the bindings:

node-hid:
sudo apt-get install libusb-1.0-0-dev libudev-dev
sudo npm install node-hid --driver=hidraw --build-from-source --unsafe-perm

serialport:
npm install serialport --build-from-source --unsafe-perm

**Comment by cfl0ws** [comment]
FYI, I experienced this same error spinning-up a new Baklava proxy. It's the first time I saw it, having spun-up over 10 nodes. Then, when spinning-up a new Baklava validator, I remembered to run this sequence - 

```
# Install Node.js and NPM

sudo apt-get update

sudo apt-get install nodejs

sudo apt-get install npm

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash

export NVM_DIR="$HOME/.nvm"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install 10 && nvm use 10
```

It seems to resolve the error, as I didn't receive it when running celocli on the new validator.
