### ISSUE TITLE
Cannot install properly, errored

### ISSUE THREAD

**Issue by dpichevin** [cncjs/cncjs-pendant-keyboard#5]
I am having trouble installing this. I have followed the same steps as for the PS3 pendant. The npm install command ends in a lot of errors, as with another issue here. Then running pm2 start responds with "process successfully started" but eventually the pm2 list command says it is "errored". I tried several different USB ports. This is on a fresh install of the CNCjs Pi image. Any of the node/npm related install steps in the CNCjs guides error out every single time. I'm of a mind to shelve the Rpi and CNCjs and go back to a Windows laptop with one of the other alternatives like bCNC or UGS. Any ideas?

Thanks!

Edit: looking at the logs, it's the same error as someone else, could not locate the bindings file. (spoiler: the steps highlighted in that other issue do not work either, 404, failed to fetch etc. and since the second step will be an npm install, I already know that one would fail miserably).

**Comment by nsfilho** [comment]
I'm closing this issue because are the same subject as other. OK? I'll implement that in a near future.

#8
